### ISSUE TITLE
Wrong color in Ruby if expression

### ISSUE THREAD

**Issue by maztak** [julien-duponchelle/vscode-rainbow-end#34] opened 2021-02-17 05:02 UTC
In the below case, the second 'end' color is wrong because of `if user.email.blank?` have no `end`.

```ruby
    def self.new_with_session(params, session)
        super.tap do |user|
            if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
                user.email = data["email"] if user.email.blank?
            end
        end
    end
```

**Comment by alexanderadam** [comment] 2022-02-23 11:21
Duplicate of #31

**Closed** 2022-07-20 02:38 UTC
